rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND410-B_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND410-M_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND410-T_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND422-B_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND422-M_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND422-T_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND426-B_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND430-M_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/ND426-T_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE1077-B_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE1077-M_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE1077-T_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE1169-B_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE1169-M_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE1169-T_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE985-B_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE985-M_Aligned.out.sam
rm /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_1/SLE985-T_Aligned.out.sam
