qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND410-B.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND410-M.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND410-T.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND422-B.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND422-M.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND422-T.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND426-B.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND430-M.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_ND426-T.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE1077-B.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE1077-M.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE1077-T.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE1169-B.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE1169-M.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE1169-T.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE985-B.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE985-M.sh
qsub -cwd -l mem_free=64G -l h_vmem=64G -pe smp 16 /home/zhangz/R/source/Rnaseq/examples/ProcessRnaseq/./processing_data/pass_2/qsub/STAR_SLE985-T.sh
